### ISSUE TITLE
Error generating episode - Failed to generate audio: Error code: 404

### ISSUE THREAD

**Issue by atxjd** [lfnovo/open_notebook#79]
I'm using the latest pull and docker-compose profile multi. 

When creating a podcast, I'm getting the following error:

`Error generating episode - Failed to generate audio: Error code: 404 - {'error': {'code': None, 'message': 'Invalid URL (POST /v1/audio/speech)', 'param': None, 'type': 'invalid_request_error'}}`

The output from the console:

```
open_notebook-1  | 2025-06-14 11:21:30.184 | INFO     | open_notebook.plugins.podcasts:generate_episode:125 - Generating episode  with config {'max_num_chunks': 8, 'min_chunk_size': 600, 'conversation_style': ['Educational'], 'roles_person1': ['Host', 'Conversationalist'], 'roles_person2': ['Expert Guest'], 'dialogue_structure': ['Deep Dive into Subtopics', 'Expert Interviews', 'Key Takeaways'], 'podcast_name': 'TEST Name', 'podcast_tagline': 'Test Tagline, 'output_language': 'English', 'user_instructions': 'Test instructions', 'engagement_techniques': ['Open-ended Questions', 'Evoking Curiosity', 'Spiritual'], 'creativity': 0.2, 'text_to_speech': {'output_directories': {'transcripts': './data/podcasts/transcripts', 'audio': './data/podcasts/audio'}, 'temp_audio_dir': './data/podcasts/audio/tmp', 'ending_message': "Thank you for listening to this episode. Don't forget to subscribe to our podcast for more interesting conversations.", 'default_tts_model': 'openai', 'openai': {'default_voices': {'question': 'alloy', 'answer': 'nova'}, 'model': 'gpt-4o-mini'}, 'audio_format': 'mp3'}} and using model gpt-4o-mini, tts model openai
open_notebook-1  | /app/.venv/lib/python3.12/site-packages/langsmith/client.py:272: LangSmithMissingAPIKeyWarning: API key must be provided when using hosted LangSmith API
open_notebook-1  |   warnings.warn(
open_notebook-1  | Error converting text to speech: Failed to generate audio: Error code: 404 - {'error': {'code': None, 'message': 'Invalid URL (POST /v1/audio/speech)', 'param': None, 'type': 'invalid_request_error'}}
open_notebook-1  | 2025-06-14 11:22:02,596 - podcastfy.client - ERROR - An error occurred in the process_content function: Failed to generate audio: Error code: 404 - {'error': {'code': None, 'message': 'Invalid URL (POST /v1/audio/speech)', 'param': None, 'type': 'invalid_request_error'}}
open_notebook-1  | 2025-06-14 11:22:02,596 - podcastfy.client - ERROR - An error occurred: Failed to generate audio: Error code: 404 - {'error': {'code': None, 'message': 'Invalid URL (POST /v1/audio/speech)', 'param': None, 'type': 'invalid_request_error'}}
open_notebook-1  | 2025-06-14 11:22:02.596 | ERROR    | open_notebook.plugins.podcasts:generate_episode:147 - Failed to generate episode : Failed to generate audio: Error code: 404 - {'error': {'code': None, 'message': 'Invalid URL (POST /v1/audio/speech)', 'param': None, 'type': 'invalid_request_error'}}
```

docker-compose.yml:

```
# Instructions on how to use the different compose profiles
# 1. Run `docker compose --profile single up` to start the app and database on the same container
# 2. Run `docker compose --profile multi up` to start the multi container with app and database separate
# 3. Run `docker compose --profile db_only up` to start the database only -- useful if developing locally
services:
  surrealdb:
    image: surrealdb/surrealdb:v2
    ports:
      - "8000:8000"
    volumes:
      - ./surreal_data:/mydata
    environment:
      - SURREAL_EXPERIMENTAL_GRAPHQL=true
    command: start --log info --user root --pass root rocksdb:/mydata/mydatabase.db
    pull_policy: always
    user: root
    profiles: [db_only, multi]
    networks:
      - app-net
  open_notebook:
    image: lfnovo/open_notebook:latest
    ports:
      - "8080:8502"
    env_file:
      - ./docker.env
    depends_on:
      - surrealdb
    pull_policy: always
    profiles: [multi]
    volumes:
      - ./notebook_data:/app/data
    networks:
      - app-net
  open_notebook_single:
    build:
      context: .
      dockerfile: Dockerfile.single
    ports:
      - "8080:8502"
    profiles:
      - single
    volumes:
      - ./.docker_data/data:/app/data
      - ./docker2.env:/app/.env
      - ./google-credentials.json:/app/google-credentials.json

networks:
  app-net:

```
